# Generated by Django 5.2.8 on 2026-06-18 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emaillogincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('password_hash', models.CharField(max_length=128)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'created_at'], name='users_email_email_c4f7ee_idx'), models.Index(fields=['phone_number', 'created_at'], name='users_email_phone_n_7dcae2_idx'), models.Index(fields=['expires_at'], name='users_email_expires_de5af7_idx')],
            },
        ),
    ]
