# Generated by Django 5.2.8 on 2026-06-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='operator_password_ciphertext',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
