# Generated by Django 5.2.8 on 2026-05-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cafe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.cafe'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cafes', to='core.faculty'),
        ),
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.cafe'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.cafe'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.product'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['cafe', 'is_active'], name='core_catego_cafe_id_f7f043_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('cafe', 'name'), name='core_category_unique_name_per_cafe'),
        ),
        migrations.AddIndex(
            model_name='cafe',
            index=models.Index(fields=['faculty', 'is_active'], name='core_cafe_faculty_91ad76_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cafe', 'status'], name='core_order_cafe_id_71d140_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cafe', 'created_at'], name='core_order_cafe_id_c0e9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='core_order_user_id_dacb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['cafe', 'category'], name='core_produc_cafe_id_92d75d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['cafe', 'is_available'], name='core_produc_cafe_id_077f14_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['cafe', 'created_at'], name='core_produc_cafe_id_ae4c7a_idx'),
        ),
    ]
