# Generated by Django 5.2.8 on 2026-05-03 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الرصيد الحالي')),
                ('link_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='كود الربط')),
                ('college', models.CharField(default='Bite Hub', max_length=100, verbose_name='الكلية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'إيداع (شحن)'), ('WITHDRAWAL', 'خصم (دفع)')], max_length=20)),
                ('source', models.CharField(choices=[('SYSTEM', 'المنظومة'), ('APP', 'التطبيق')], default='SYSTEM', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
    ]
