# Generated by Django 5.2.8 on 2026-06-19 01:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cafe_operator_password_ciphertext'),
        ('wallet', '0003_transaction_cafe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDebitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار موافقة الطالب'), ('APPROVED', 'وافق الطالب'), ('REJECTED', 'رفض الطالب')], db_index=True, default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_debit_requests', to='core.cafe')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_wallet_debits', to=settings.AUTH_USER_MODEL)),
                ('transaction_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_request', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_requests', to='wallet.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['wallet', 'status', 'created_at'], name='wallet_wall_wallet__a6483b_idx'), models.Index(fields=['cafe', 'status', 'created_at'], name='wallet_wall_cafe_id_fb7ec3_idx')],
            },
        ),
    ]
