# Generated by Django 5.2.8 on 2026-06-29 15:17

import secrets
import string

from django.db import migrations, models


ALPHABET = string.ascii_uppercase + string.digits


def _generate_code():
    return "".join(secrets.choice(ALPHABET) for _ in range(16))


def rotate_weak_wallet_codes(apps, schema_editor):
    Wallet = apps.get_model("wallet", "Wallet")
    used_codes = set()

    for wallet in Wallet.objects.all().order_by("pk").iterator():
        current = (wallet.link_code or "").strip().upper()
        is_strong = (
            12 <= len(current) <= 32
            and all(char in ALPHABET or char in "_-" for char in current)
        )
        if is_strong and current not in used_codes:
            if wallet.link_code != current:
                wallet.link_code = current
                wallet.save(update_fields=["link_code"])
            used_codes.add(current)
            continue

        candidate = _generate_code()
        while candidate in used_codes:
            candidate = _generate_code()
        used_codes.add(candidate)
        wallet.link_code = candidate
        wallet.save(update_fields=["link_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_walletdebitrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='link_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='كود الربط'),
        ),
        migrations.RunPython(rotate_weak_wallet_codes, migrations.RunPython.noop),
    ]
