# Generated by Django 5.2.8 on 2026-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_enforce_student_wallet_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('SYSTEM', 'المنظومة'), ('APP', 'التطبيق'), ('USER', 'المستخدم')], default='SYSTEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'شحن'), ('WITHDRAWAL', 'خصم (دفع)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='link_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='كود المحفظة'),
        ),
    ]
